name: 'Test Fetch Latest Tag Action'

on: [push]

jobs:
  fetch-latest-tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Fetch Latest Tag
      id: fetch-latest-tag
      uses: brainxio/fetch-latest-tag@main
      with:
        owner: 'octocat'
        repo: 'Hello-World'

    - name: Print Latest Tag
      run: echo "Latest Tag: ${{ steps.fetch-latest-tag.outputs['latest-tag'] }}"
